In [1]:
import pandas as pd 
import numpy as np

In [2]:
# Load Excel dataset from Downloads folder
file_path = r"C:\Users\ashwa\Downloads\sugar_cosmetics_instagram_data.xlsx"
df = pd.read_excel(file_path)

In [3]:
df.head()

,Post Date,Post Type,Campaign Type,Hashtags,Audience Emotion,Engagement Source,Impressions,Reach,Likes,Comments,Shares,Saves,Profile Visits,Follows
0,2024-12-23,Story,Giveaway,"#SugarCosmetics, #MakeupGoals, #BoldLooks",Curious,Collab,16795,15665,3076,430,73,99,193,86
1,2024-06-01,Image,Tutorial,"#BoldLooks, #MakeupGoals, #VeganBeauty",Confident,Influencer,45131,29335,5285,308,396,502,294,146
2,2024-04-28,Reel,Festive Offer,#VeganBeauty,Confident,Collab,18568,13118,2032,233,73,140,204,44
3,2025-02-01,Reel,Product Launch,"#CrueltyFree, #VeganBeauty, #SugarCosmetics",Happy,Collab,1189,751,130,13,12,7,33,12
4,2024-08-04,Story,Tutorial,"#SugarCosmetics, #VeganBeauty",Curious,Organic,15502,9373,2234,300,99,47,180,35

In [6]:
# Check the number of rows and columns
print("number of rows:", df.shape[0])
print("number of columns:", df.shape[1])

number of rows: 50000
number of columns: 14

In [7]:
# Display all column names
print(df.columns.tolist())

['Post Date', 'Post Type', 'Campaign Type', 'Hashtags', 'Audience Emotion', 'Engagement Source', 'Impressions', 'Reach', 'Likes', 'Comments', 'Shares', 'Saves', 'Profile Visits', 'Follows']

In [9]:
# Dataset structure and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Post Date          50000 non-null  datetime64[ns]
 1   Post Type          50000 non-null  object
 2   Campaign Type      50000 non-null  object
 3   Hashtags           50000 non-null  object
 4   Audience Emotion   50000 non-null  object
 5   Engagement Source  50000 non-null  object
 6   Impressions        50000 non-null  int64
 7   Reach              50000 non-null  int64
 8   Likes              50000 non-null  int64
 9   Comments           50000 non-null  int64
 10  Shares             50000 non-null  int64
 11  Saves              50000 non-null  int64
 12  Profile Visits     50000 non-null  int64
 13  Follows            50000 non-null  int64
dtypes: datetime64[ns](1), int64(8), object(5)
memory usage: 5.3+ MB

In [10]:
# Count missing values in each column
df.isnull().sum()

Post Date            0
Post Type            0
Campaign Type        0
Hashtags             0
Audience Emotion     0
Engagement Source    0
Impressions          0
Reach                0
Likes                0
Comments             0
Shares               0
Saves                0
Profile Visits       0
Follows              0
dtype: int64

In [11]:
# Statistical summary of numerical columns
df.describe()

,Post Date,Impressions,Reach,Likes,Comments,Shares,Saves,Profile Visits,Follows
count,50000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000
mean,2024-10-17 22:51:23.904000512,25520.915000,19748.465760,2954.565580,369.187220,162.306760,177.22878,592.695960,177.334200
min,2024-04-19 00:00:00,1002.000000,616.000000,40.000000,2.000000,0.000000,1.00000,7.000000,0.000000
25%,2024-07-18 00:00:00,13243.000000,10157.750000,1256.000000,135.000000,50.000000,62.00000,252.000000,63.000000
50%,2024-10-18 00:00:00,25541.000000,19393.500000,2466.000000,282.000000,114.000000,132.00000,497.000000,133.000000
75%,2025-01-17 00:00:00,37758.250000,28763.250000,4255.000000,516.000000,228.000000,246.00000,851.000000,245.000000
max,2025-04-19 00:00:00,49999.000000,47329.000000,11392.000000,2205.000000,1072.000000,1057.00000,2264.000000,1114.000000
std,NaN,14118.653466,11311.962456,2144.918922,311.676485,151.722516,154.94933,428.221806,154.550825

In [13]:
# Check exact duplicate rows
duplicate_count = df.duplicated().sum()
duplicate_count

np.int64(0)

In [18]:
# Select numerical columns
numeric_columns = df.select_dtypes(include="number").columns
# Count zero values
print("Zero Values in Each Numerical Column:")
print((df[numeric_columns] == 0).sum())
# Count negative values
print("\nNegative Values in Each Numerical Column:")
print((df[numeric_columns] < 0).sum())

Zero Values in Each Numerical Column:
Impressions       0
Reach             0
Likes             0
Comments          0
Shares            9
Saves             0
Profile Visits    0
Follows           1
dtype: int64

Negative Values in Each Numerical Column:
Impressions       0
Reach             0
Likes             0
Comments          0
Shares            0
Saves             0
Profile Visits    0
Follows           0
dtype: int64

In [20]:
# Check whether Reach exceeds Impressions
invalid_reach = df[df["Reach"] > df["Impressions"]]
print("Records Where Reach Exceeds Impressions:", len(invalid_reach))

Records Where Reach Exceeds Impressions: 0

In [21]:
# Inspect unique categorical values
categorical_columns = [
    "Post Type",
    "Campaign Type",
    "Audience Emotion",
    "Engagement Source"
]

for col in categorical_columns:
    print(f"\nUnique values in {col}:")
    print(df[col].value_counts())

Unique values in Post Type:
Post Type
Reel     12599
Story    12517
Video    12485
Image    12399
Name: count, dtype: int64

Unique values in Campaign Type:
Campaign Type
Tutorial             10186
Giveaway              9998
Festive Offer         9990
Product Launch        9923
Influencer Collab     9903
Name: count, dtype: int64

Unique values in Audience Emotion:
Audience Emotion
Inspired     10137
Excited      10061
Curious      10027
Confident     9891
Happy         9884
Name: count, dtype: int64

Unique values in Engagement Source:
Engagement Source
Collab        12633
Organic       12508
Influencer    12501
Paid          12358
Name: count, dtype: int64

In [24]:
# Display the first 10 hashtag entries
df["Hashtags"].head(10)

0      #SugarCosmetics, #MakeupGoals, #BoldLooks
1         #BoldLooks, #MakeupGoals, #VeganBeauty
2                                   #VeganBeauty
3    #CrueltyFree, #VeganBeauty, #SugarCosmetics
4                  #SugarCosmetics, #VeganBeauty
5                                #SugarCosmetics
6                  #CrueltyFree, #SugarCosmetics
7                                   #CrueltyFree
8    #SugarCosmetics, #VeganBeauty, #MakeupGoals
9                     #MakeupGoals, #CrueltyFree
Name: Hashtags, dtype: object

In [26]:
# Count the number of hashtags in each record
hashtag_count = (
    df["Hashtags"]
    .fillna("")
    .apply(lambda x: len([tag for tag in x.split(",") if tag.strip()]))
)

print("Minimum hashtags per record:", hashtag_count.min())
print("Maximum hashtags per record:", hashtag_count.max())
print("Average hashtags per record:", round(hashtag_count.mean(), 2))

Minimum hashtags per record: 1
Maximum hashtags per record: 3
Average hashtags per record: 2.0

In [28]:
# Check the earliest and latest dates
print("Earliest Post Date:", df["Post Date"].min())
print("Latest Post Date:", df["Post Date"].max())
# Check for dates outside the expected project period
start_date = pd.Timestamp("2024-04-19")
end_date = pd.Timestamp("2025-04-19")

invalid_dates = df[
    (df["Post Date"] < start_date) |
    (df["Post Date"] > end_date)
]
print("Records Outside Expected Date Range:", len(invalid_dates))

# Check for missing dates
print("Missing Post Dates:", df["Post Date"].isna().sum())

Earliest Post Date: 2024-04-19 00:00:00
Latest Post Date: 2025-04-19 00:00:00
Records Outside Expected Date Range: 0
Missing Post Dates: 0

In [29]:
# Check for leading/trailing spaces and inconsistent capitalization

text_columns = [
    "Post Type",
    "Campaign Type",
    "Audience Emotion",
    "Engagement Source"
]

for col in text_columns:
    print(f"\nColumn: {col}")
    print("Unique values:", df[col].nunique())

    # Check values containing leading or trailing spaces
    spaces = df[col].astype(str).ne(df[col].astype(str).str.strip()).sum()
    print("Values with extra spaces:", spaces)

    # Display the unique values
    print(df[col].value_counts())

Column: Post Type
Unique values: 4
Values with extra spaces: 0
Post Type
Reel     12599
Story    12517
Video    12485
Image    12399
Name: count, dtype: int64

Column: Campaign Type
Unique values: 5
Values with extra spaces: 0
Campaign Type
Tutorial             10186
Giveaway              9998
Festive Offer         9990
Product Launch        9923
Influencer Collab     9903
Name: count, dtype: int64

Column: Audience Emotion
Unique values: 5
Values with extra spaces: 0
Audience Emotion
Inspired     10137
Excited      10061
Curious      10027
Confident     9891
Happy         9884
Name: count, dtype: int64

Column: Engagement Source
Unique values: 4
Values with extra spaces: 0
Engagement Source
Collab        12633
Organic       12508
Influencer    12501
Paid          12358
Name: count, dtype: int64

In [30]:
# Check missing hashtags
print("Missing hashtags:", df["Hashtags"].isna().sum())

# Check empty or whitespace-only hashtags
empty_hashtags = df["Hashtags"].astype(str).str.strip().eq("").sum()

print("Empty hashtags:", empty_hashtags)

# Display unique hashtags strings
print("Unique hashtag combinations:", df["Hashtags"].nunique())

Missing hashtags: 0
Empty hashtags: 0
Unique hashtag combinations: 85

In [31]:
# Check for negative values in numerical columns
numeric_columns = df.select_dtypes(include="number").columns

negative_counts = (df[numeric_columns] < 0).sum()

print("Negative values by column:")
print(negative_counts)

print("\nTotal negative values:", negative_counts.sum())

Negative values by column:
Impressions       0
Reach             0
Likes             0
Comments          0
Shares            0
Saves             0
Profile Visits    0
Follows           0
dtype: int64

Total negative values: 0